### ISSUE TITLE
Проверить 4.Issue

### ISSUE THREAD

**Issue by mazanur** [almaznur91/4.Issue#1]
Не совсем понял где это нужно сделать "пропишите URL
вашего сервиса на Heroku." https://spring-boot-issue.herokuapp.com/ 

В связи с этим ничего и не отображается на Heroku

**Comment by coursar** [comment]
Чтобы frontend ходил на backend, есть несколько вариантов, среди которых:
1. Развернуть фронтенд внутри Spring'а (тогда вот тут: https://github.com/almaznur91/4.Issue/blob/79ecb130ffbbe146d77ee46ee5633919a91592a8/frontend/app.js#L52 достаточно писать `/api`)
2. Развернуть фронт и бэк отдельно (тогда вот тут: https://github.com/almaznur91/4.Issue/blob/79ecb130ffbbe146d77ee46ee5633919a91592a8/frontend/app.js#L52 нужно писать: `http://my-service.herokuapp.com/api`)
